### ISSUE TITLE
Adicionar lista com currículos de universidades "AAA"

### ISSUE THREAD

**Issue by paladini** [CalicoUFSC/ufsc-cco-reformulado#1]
Recomendo adicionar uma lista contendo os currículos de universidades grandes do Brasil e do mundo em Ciência da Computação.

Esses currículos poderão ser usados como um modelo parcial para utilizar no currículo do nosso curso. 

**Algumas sugestões:**
- MIT
- Stanford
- Harvard
- Princeton
- USP
- (aquela federal do nordeste que é muito boa, acho que do Rio Grande do Norte)

**Comment by ranisalt** [comment]
Sim, essa é a ideia :D pretendo colocar uma lista de referências assim que eu encontrar mais.

Se tiver mais sugestões, posta aí. Marquei como "help wanted".

**Comment by zambonin** [comment]
adicionando algo de útil ao tópico, a universidade que o @paladini quis citar é a Universidade Federal de Pernambuco, fortíssima em algoritmos e a líder em programadores no Brasil.

ademais, visto que isso é um registro de como o currículo poderia ser reformulado, um dos pilares do argumento é a comparação às universidades de maior qualidade (principalmente no âmbito brasileiro). portanto, UFMG e UFRGS são outras possibilidades a se considerar.

**Comment by ranisalt** [comment]
UFMG é top mesmo, especialmente na carreira acadêmica, eles tem o melhor mestrado e doutorado do Brasil atualmente, acho até que os únicos 7/7

**Comment by zambonin** [comment]
segundo fonte da CAPES [aqui](http://conteudoweb.capes.gov.br/conteudoweb/ProjetoRelacaoCursosServlet?acao=pesquisarIes&codigoArea=10300007&descricaoArea=CI%CANCIAS+EXATAS+E+DA+TERRA+&descricaoAreaConhecimento=CI%CANCIA+DA+COMPUTA%C7%C3O&descricaoAreaAvaliacao=CI%CANCIA+DA+COMPUTA%C7%C3O), o que estamos procurando são as seguintes: UFMG, UFRGS e Unicamp, seguidas da USP e UFPE. 

comparativamente, temos uma mera nota 4/7 e uma [avaliação mediana](http://conteudoweb.capes.gov.br/conteudoweb/VisualizadorServlet?nome=41001010/002/2013_002_41001010025P2_Ficha.pdf&aplicacao=avaliacaotrienal&idEtapa=2&ano=2013&tipo=divulga).

**Comment by paladini** [comment]
Talvez seja interessante criar uma outra issue para falar sobre qual deve ser o foco do novo currículo, o que acham? 

Pois dependendo do que queremos focar, ficamos restritos a algumas universidades mais específicas.

**Comment by ranisalt** [comment]
4 é um lixo, considerando que o índice vai de 3 (mínimo aceitável) a 7. na prática, é 2/4

pode abrir um issue, Paladini :) e se quiser pode mandar PR também com alterações

**Comment by paladini** [comment]
@ranisalt , que professores estão colaborando com a ideia? Acho importante chamar mais gente importante pra cá, tipo o Mário Dantas (coordenador) e outros representantes do curso, o que acha?

**Comment by ranisalt** [comment]
Acredito que o Dantas seja bastante aberto à sugestões de alunos. Os professores novos em geral, na verdade. Os mais antigos é que acho difícil cederem a ideia porque vão ter que sair da zona de conforto.

**Comment by paladini** [comment]
@ranisalt Como membro do Colegiado, já estou em contato com o Dantas há algum tempo e ele quer sim fazer mudanças no curso. As conversas já vinham desde a época com o Mazzola, mas devido à baixa frequência das reuniões do Colegiado isso nunca foi conversado como deveria.

Estou esperançoso que agora isso seja possível e que possamos finalmente tornar o nosso curso mais científico ou mais concernente aos demais cursos de ciência da computação do mundo (pelo menos é essa a minha visão do curso, puxar mais pra ciência, matemática e computação de fato, não para Sistemas da Informação). Mas é uma opinião pessoal, como representante do curso no Colegiado não posso levar muito em conta ela.
