### ISSUE TITLE
Inclusão das disciplinas do PAM no rol de optativas do curso

### ISSUE THREAD

**Issue by royertiago** [CalicoUFSC/ufsc-cco-reformulado#11]
O programa avançado de matemática (PAM - http://pam.mtm.ufsc.br/) é um conjunto de disciplinas oferecidas pelo departamento de Matemática que contempla principalmente cálculo e álgebra linear. Mas, diferentemente das disciplinas correspondentes que temos no nosso currículo, as do PAM possuem um viés muito forte na formação matemática do aluno; isto é, a habilidade de entender e construir definições e demonstrações matemáticas.

O PAM segue o estilo definição-teorema-prova-corolário dos livros de matemática avançados; é o mesmo estilo dos livros "canônicos" das áreas um pouco mais teóricas da Ciência da Computação, como Algoritmos (Knuth, Cormen & cia), Matemática Discreta (Rosen, Kolman & cia), Teoria da Computação (Hopcroft e Ullman, Sipser), e Criptografia (Stinson, Trappe e Washington). (Incluiria aqui também Grafos, mas não sei apontar um livro "canônico".)

Como ex-aluno do PAM, posso dizer que a habilidade de definir e analisar conceitos formalmente facilitou muito o meu entendimento de diversas áreas no curso (grafos, teoria da computação, linguagens formais, programação em lógica, programação funcional, cálculo numérico, criptografia), mesmo em disciplinas não diretamente relacionadas à matemática (por exemplo, circuitos digitais e mapas de Karnaugh, projeto de sistemas digitais, árvores e ordenação, álgebra relacional e SQL, lógica fuzzy e redes neurais).

Penso que as disciplinas do PAM deveriam, ao menos, ser optativas do nosso currículo (assim como nos currículos das engenharias Civil, Mecânica e Química, por exemplo), para incentivar os alunos com um viés teórico a cursarem estas disciplinas.

**Comment by paladini** [comment]
@royertiago , acho que uma ótima ideia para ser discutida, entretanto as disciplinas do PAM já não podem validar todas as disciplinas de matemática do nosso curso (com exceção de discreta)?

Se sim, ainda faria sentido manter a proposta de colocá-las como optativas? Por que?

**Comment by royertiago** [comment]
PAM valida apenas cálculo A e B e álgebra linear; ficam sobrando matemática discreta, geometria analítica, probabilidade e estatística e cálculo numérico.

Tecnicamente, estas disciplinas não validam as correspondentes no nosso curso; nós apenas ficamos "dispensados de cursar" a disciplina equivalente. Para me matricular em cálculo numérico, que depende de cálculo B, tive que falar diretamente com o Mazzola (então coordenador do curso), pois eu tinha apenas H-Cálculo II. Este é um "bug" menor que existe em nosso currículo.

**Comment by GNakayama** [comment]
Acho que o PAM ja está disponível pra quem se interessar, colocar ele ou não dentro das optativas do curso não faria tanta diferença pro curriculo. O que seria interessante seria criar algo nos moldes do PAM para a computação, tipo um Programa Avançado para Computação(PAC Lula e Dilma curtem), envolvendo tópicos na área de algoritmos e matemática que não são oferecidos dentro da grade padrão do curso. Talvez poderiamos aproveitar as matérias dadas pelo PAM dentro desse programa.

**Comment by paladini** [comment]
@GNakayama a ideia é fantástica, problema é achar professores interessados, sem falar no investimento que teria que ter. 

Eu acho que concordo com o @royertiago de que seria interessante colocar as disciplinas do PAM como optativas, pois assim quando tivessemos que cursar as "optativas obrigatórias" (aquele número X de horas-aula que temos que cursar de optativas) poderiamos escolher as disciplinas do PAM ou validá-las, caso já tivessemos feito.

**Comment by zambonin** [comment]
vejo muitos alunos de computação procurando matérias optativas, seja por interesse próprio ou por necessidade de cumprir currículo. o que eu não vejo é um rol diverso de matérias como acontece em outras universidades brasileiras.

expandir a lista atual de optativas através do PAM é uma ótima sugestão. não fogem do escopo do curso -- provavelmente o contrário acontece, como o @royertiago expandiu no terceiro parágrafo -- e podem servir para validar tanto matérias de computação quanto matérias extra-curriculares que também temos a necessidade de cursar. (e ainda sobra!)

**Comment by ranisalt** [comment]
Não há a possibilidade de criar matérias optativas ministradas por alunos, e não por professores? Já temos várias aulas assim extraoficialmente, acho que um incentivo a mais faria nosso currículo ficar bem recheado com experiências dos próprios alunos e nenhuma universidade par.

@royertiago poderia fazer um PR adicionando as matérias do PAM como optativas?

**Comment by zambonin** [comment]
o máximo que se pode fazer nesse caso são minicursos estilo linux que o PET da computação promove há alguns semestres. ganha-se certificado mas não conta pro currículo.

pra ser docente na universidade é necessário, no mínimo, graduação completa pra ser professor substituto. pra dar aula no nosso departamento, nunca vi nenhum professor sem no mínimo mestrado...

**Comment by ranisalt** [comment]
Vamos mover a discussão para #12
