### ISSUE TITLE
Como contribuir?

### ISSUE THREAD

**Issue by paladini** [CalicoUFSC/ufsc-cco-reformulado#3]
Acho que é interessante criar uma seção de como contribuir lá no README. Eu, por exemplo, quero contribuir mas não sei quais são os planos do projeto e o que eu poderia ir fazendo para ajudar.

Talvez um planejamento com uma todo list pública seja interessante para angariar mais ajuda. O que acham?

**Comment by zambonin** [comment]
o plano é abrir um PR a cada grande mudança, com espaço para comentários e commits. muitos serão propostos pelos contribuidores, mas qualquer um pode dar sugestões.

entretanto, se quiser contribuir com um PR, é importante lembrar que a argumentação deve ser concisa e bem-construída, pensando no bem do conjunto total de alunos e na sua formação acadêmica final.

**Comment by ranisalt** [comment]
No clássico fork-merge request mesmo, aí posta no grupo de cco e se tiver boa argumentação e quorum a gente dá mercê.
